rootUrl: http://localhost:8000
gridUrl: http://ondemand.saucelabs.com/wd/hub
browsers:
  firefox-v30:
    browserName: firefox
    version: 30
    platform: Linux
  chrome-v35:
    browserName: chrome
    version: 35
    platform: Linux
  opera-v12:
    browserName: opera
    version: 12
    platform: Windows 7
