language: node_js
node_js:
- '0.10'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y graphicsmagick

before_script: |
  echo "capabilities:" >> .gemini.yml
  echo "  tunnel-identifier: '${TRAVIS_JOB_NUMBER}'" >> .gemini.yml
  npm start
  sleep 3
addons:
  sauce_connect:
    username: SevInf
    access_key:
      secure: E1gnaExfF061JHD7+CJTDAzLuxfcB4c2pF05i0huCaGRBN7uB+pkkkcd6u25KtjQ07PgIpKCBXu/oRknlthu6D6vK/cPYRO31hIhFN2VSPwxQ43UTj/Z4pUkTUErxrh8tlaY8zY87DjrkMIypHAZ1PJMqNrvCvvIe7WKCElm+6U=
